project:
  type: website
  output-dir: docs
date: last-modified

execute:
  cache: false

book:
  title: "Altair for Mathematicians"
  author: "Thomas Camminady"
  description: How to use Altair as a Mathematician.
  keyword: altair, pandas, python, mathematics
  url: https://thomascamminady.github.io/altair_for_mathematicians/
  sidebar:
    search: true
  repo-url: https://github.com/thomascamminady/altair_for_mathematicians
  repo-branch: main
  repo-actions: [edit, issue, source]
  sharing: [twitter, facebook, linkedin]


website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Differential equations"
        contents:
          - notebooks/1a_predator_prey_model.qmd
          -  notebooks/1b_van_der_pol.qmd
  navbar:
    background: primary
    search: true
    left:
      - text: "Altair for Mathematicians"
        file: index.qmd

format:
  html:
    code-fold: false
    code-tools: true
    code-copy: true
    code-link: true
    highlight-style: dracula
    code-line-numbers: true

    theme:
      - cosmo
      - custom.scss
    toc: true
    fontsize: 1.2em
    linestretch: 1.7
