project:
  type: website
  output-dir: docs

date: last-modified

execute:
  cache: false


website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - section: "Matrices"
        contents:
          - notebooks/matrices.qmd
      - section: "Differential equations"
        contents:
          - notebooks/predator_prey_model.qmd
          - notebooks/van_der_pol.qmd


format:
  html:
    code-fold: false
    code-tools: true
    code-copy: true
    code-link: true
    highlight-style: dracula
    code-line-numbers: true

    theme:
      - cosmo
    toc: true
    fontsize: 1.2em
    linestretch: 1.7
